package com.monk.reader.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.monk.reader.dao.bean.ShelfBook;
import com.monk.reader.dao.bean.BookCatalogue;
import com.monk.reader.dao.model.StoryArticle;

import com.monk.reader.dao.ShelfBookDao;
import com.monk.reader.dao.BookCatalogueDao;
import com.monk.reader.dao.StoryArticleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shelfBookDaoConfig;
    private final DaoConfig bookCatalogueDaoConfig;
    private final DaoConfig storyArticleDaoConfig;

    private final ShelfBookDao shelfBookDao;
    private final BookCatalogueDao bookCatalogueDao;
    private final StoryArticleDao storyArticleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shelfBookDaoConfig = daoConfigMap.get(ShelfBookDao.class).clone();
        shelfBookDaoConfig.initIdentityScope(type);

        bookCatalogueDaoConfig = daoConfigMap.get(BookCatalogueDao.class).clone();
        bookCatalogueDaoConfig.initIdentityScope(type);

        storyArticleDaoConfig = daoConfigMap.get(StoryArticleDao.class).clone();
        storyArticleDaoConfig.initIdentityScope(type);

        shelfBookDao = new ShelfBookDao(shelfBookDaoConfig, this);
        bookCatalogueDao = new BookCatalogueDao(bookCatalogueDaoConfig, this);
        storyArticleDao = new StoryArticleDao(storyArticleDaoConfig, this);

        registerDao(ShelfBook.class, shelfBookDao);
        registerDao(BookCatalogue.class, bookCatalogueDao);
        registerDao(StoryArticle.class, storyArticleDao);
    }
    
    public void clear() {
        shelfBookDaoConfig.clearIdentityScope();
        bookCatalogueDaoConfig.clearIdentityScope();
        storyArticleDaoConfig.clearIdentityScope();
    }

    public ShelfBookDao getShelfBookDao() {
        return shelfBookDao;
    }

    public BookCatalogueDao getBookCatalogueDao() {
        return bookCatalogueDao;
    }

    public StoryArticleDao getStoryArticleDao() {
        return storyArticleDao;
    }

}
